# Mod
mod_name = Kits
mod_id = kits
mod_version = 1.9.0

# Fabric
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.152.1+26.2

# Dependencies
permissions_api_version=0.7.0
sgui_version=2.1.0+26.2

jetbrains_annotations_version = 23.0.0
junit_bom_version = 5.10.1

# Modrinth
mr_project_id = yeVTVdYd
mr_game_versions = 26.1.1
mr_relations_required = fabric-api
mr_relations_optional =
mr_relations_embedded = fabric-permissions-api
mr_relations_incompatible =

# CurseForge
cf_project_id = 507127
cf_game_versions = Fabric,Java 25,26.1.1
cf_relations_required = fabric-api
cf_relations_optional =
cf_relations_embedded =
cf_relations_tools =
cf_relations_incompatible =

# Publish
maven_group = dev.jpcode.kits
github_repo = John-Paul-R/kits
gh_owner = John-Paul-R
gh_repo = kits
game_versions = 26.1.1


# Other
org.gradle.jvmargs=-Xmx1G
